services:
  db:
    image: postgres:18.1-alpine3.23
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER} -d ${DB_NAME}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

    command:
      - postgres
      - -c
      - tcp_keepalives_idle=600
      - -c
      - tcp_keepalives_interval=30
      - -c
      - tcp_keepalives_count=10

    volumes:
      - postgres_data:/var/lib/postgresql/data


  migrations:
    build:
      context: .
      dockerfile: Dockerfile
      target: migrations

    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy


  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: bot

    restart: unless-stopped

    init: true

    env_file:
      - .env

    depends_on:
      migrations:
        condition: service_completed_successfully

      db:
        condition: service_healthy


  adminer:
    image: adminer:5
    restart: unless-stopped

    profiles:
      - dev

    ports:
      - "127.0.0.1:8080:8080"


volumes:
  postgres_data:
